In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = np.load('../assets/proyecto_training_data.npy')
data

array([[2.08500e+05, 7.00000e+00, 8.56000e+02, 8.00000e+00, 2.00300e+03,
        6.50000e+01],
       [1.81500e+05, 6.00000e+00, 1.26200e+03, 6.00000e+00, 1.97600e+03,
        8.00000e+01],
       [2.23500e+05, 7.00000e+00, 9.20000e+02, 6.00000e+00, 2.00100e+03,
        6.80000e+01],
       ...,
       [2.66500e+05, 7.00000e+00, 1.18800e+03, 9.00000e+00, 1.94100e+03,
        6.60000e+01],
       [1.42125e+05, 5.00000e+00, 1.07800e+03, 5.00000e+00, 1.95000e+03,
        6.80000e+01],
       [1.47500e+05, 5.00000e+00, 1.25600e+03, 6.00000e+00, 1.96500e+03,
        7.50000e+01]])

In [4]:
n = len(data)
n80 = int(n * 0.8)

In [5]:
data_training = data[0:n80]
data_testing = data[n80:n]
data_training

array([[2.0850e+05, 7.0000e+00, 8.5600e+02, 8.0000e+00, 2.0030e+03,
        6.5000e+01],
       [1.8150e+05, 6.0000e+00, 1.2620e+03, 6.0000e+00, 1.9760e+03,
        8.0000e+01],
       [2.2350e+05, 7.0000e+00, 9.2000e+02, 6.0000e+00, 2.0010e+03,
        6.8000e+01],
       ...,
       [2.3317e+05, 7.0000e+00, 1.5020e+03, 7.0000e+00, 2.0090e+03,
        7.9000e+01],
       [2.4535e+05, 8.0000e+00, 1.6940e+03, 7.0000e+00, 2.0080e+03,
        6.4000e+01],
       [1.7300e+05, 6.0000e+00, 9.5900e+02, 7.0000e+00, 2.0000e+03,
        5.8000e+01]])

In [6]:
training_df = pd.DataFrame(data_training, columns=['SalePrice', 'OverallQual', '1stFlrSF', 'TotRmsAbvGrd', 'YearBuilt', 'LotFrontage'])
training_df

SalePrice  OverallQual  1stFlrSF  TotRmsAbvGrd  YearBuilt  LotFrontage
0      208500.0          7.0     856.0           8.0     2003.0         65.0
1      181500.0          6.0    1262.0           6.0     1976.0         80.0
2      223500.0          7.0     920.0           6.0     2001.0         68.0
3      140000.0          7.0     961.0           7.0     1915.0         60.0
4      250000.0          8.0    1145.0           9.0     2000.0         84.0
...         ...          ...       ...           ...        ...          ...
1163   108959.0          4.0    1258.0           6.0     1969.0         60.0
1164   194000.0          5.0    1432.0           5.0     1978.0          NaN
1165   233170.0          7.0    1502.0           7.0     2009.0         79.0
1166   245350.0          8.0    1694.0           7.0     2008.0         64.0
1167   173000.0          6.0     959.0           7.0     2000.0         58.0

[1168 rows x 6 columns]

In [7]:
variables_x1 = training_df['OverallQual']
variables_x2 = training_df['1stFlrSF']
variables_y = training_df['SalePrice']
variables_y

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...   
1163    108959.0
1164    194000.0
1165    233170.0
1166    245350.0
1167    173000.0
Name: SalePrice, Length: 1168, dtype: float64

In [26]:
alpha = 0.001
epochs = 10
imprimir_error_cada = 1
b0 = 30324.585174963722
b1 = 129.9512422871571

In [28]:
x = np.array(variables_x2)
y_real = np.array(variables_y)
vect1 = np.ones_like(x).reshape(-1, 1)
x = np.reshape(x, (-1, 1))
A = np.hstack([x, vect1])
betas = np.array([b1, b0]).reshape(-1, 1)
error_array = []
betas

array([[  129.95124229],
       [30324.58517496]])

In [29]:
variables_x2

0        856.0
1       1262.0
2        920.0
3        961.0
4       1145.0
         ...  
1163    1258.0
1164    1432.0
1165    1502.0
1166    1694.0
1167     959.0
Name: 1stFlrSF, Length: 1168, dtype: float64

In [30]:
A

array([[8.560e+02, 1.000e+00],
       [1.262e+03, 1.000e+00],
       [9.200e+02, 1.000e+00],
       ...,
       [1.502e+03, 1.000e+00],
       [1.694e+03, 1.000e+00],
       [9.590e+02, 1.000e+00]])

In [31]:
y_calculada = np.dot(A, betas)
y_calculada

array([[141562.84857277],
       [194323.05294136],
       [149879.72807915],
       ...,
       [225511.35109027],
       [250461.98960941],
       [154947.82652835]])

In [23]:
variable_x = np.array(variables_x2)
constante_1 = np.empty(n80)
constante_1.fill(1)
observacion = np.column_stack((variable_x, constante_1))
b0 = 30324.585174963722
b1 = 129.9512422871571
parametros = np.array([b1, b0])
observacion

array([[8.560e+02, 1.000e+00],
       [1.262e+03, 1.000e+00],
       [9.200e+02, 1.000e+00],
       ...,
       [1.502e+03, 1.000e+00],
       [1.694e+03, 1.000e+00],
       [9.590e+02, 1.000e+00]])

In [24]:
parametros

array([  129.95124229, 30324.58517496])

In [25]:
y_calculada = np.dot(observacion, parametros)
y_calculada

array([141562.84857277, 194323.05294136, 149879.72807915, ...,
       225511.35109027, 250461.98960941, 154947.82652835])

In [32]:
y_real = np.array(variables_y)
y_real

array([208500., 181500., 223500., ..., 233170., 245350., 173000.])

In [33]:
error1 = np.mean(np.power(y_real - y_calculada, 2))
error1

8563933908.128045

In [34]:
error2 = np.mean(np.power(y_real - y_calculada, 2)) / 2
error2

4281966954.0640225

In [10]:
for i in range(epochs):
    y_calculada = np.dot(A, betas)
    error = np.mean(np.power(y_real - y_calculada, 2)) / 2
    
    gradiente_b0 = np.mean(y_real - y_calculada)
    gradiente_b1 = np.mean(np.dot(y_real - y_calculada, x))
    
    b0 = b0 - (alpha*gradiente_b0)
    b1 = b1 - (alpha*gradiente_b1)
    betas = np.array([b1, b0]).reshape(-1, 1)
    
    error_array.append(error)
    
    if (i + 1) % imprimir_error_cada == 0:
        print(f'El error es de: {error}')

El error es de: 4281966954.0640225
El error es de: 3.31454121510722e+20
El error es de: 8.084037675074736e+32
El error es de: 1.971660674196047e+45
El error es de: 4.808792302083372e+57
El error es de: 1.172842959603351e+70
El error es de: 2.8605115827007042e+82
El error es de: 6.976659959260173e+94
El error es de: 1.7015761964225154e+107
El error es de: 4.150068326590401e+119
